### ISSUE TITLE
Issue with GDELT node features

### ISSUE THREAD

**Issue by CongWeilin** [amazon-research/tgl#10]
The node features are all the same:

```
import torch
node_feats = torch.load('DATA/GDELT/node_features.pt')
if node_feats.dtype == torch.bool:
    node_feats = node_feats.type(torch.float32)
torch.unique(node_feats.argmax(dim=1))
```

Gives us output `tensor([79])`

The `node_features.pt` is downloaded by `wget -P ./DATA/GDELT https://s3.us-west-2.amazonaws.com/dgl-data/dataset/tgl/GDELT/node_features.pt`

**Comment by tedzhouhk** [comment]
Hi, thanks for pointing this out. I believe I have uploaded the wrong version of the GDELT dataset to the s3 bucket. I will upload the correct version (this might take a while as these datasets are generated last year when I was a intern at AWS).

**Comment by tedzhouhk** [comment]
Hi, I have re-upload the dataset. Please download ALL FILES in the GDELT folder from the s3 bucket. I'll also notice it in the readme. Thanks.
