### ISSUE TITLE
Question on WIKI and Reddit Data

### ISSUE THREAD

**Issue by yw6vp** [amazon-research/tgl#14]
Hello, my question is closely related to this issue: https://github.com/amazon-research/tgl/issues/5. 

Basically, I'd like to confirm if my understanding is correct. In the issue above, it said both WIKI and Reddit graphs are undirected. Take WIKI data as an example, does that mean if an user U edited a page P at time T, there will be two edges in edges.csv: 1. U as source node and P as destination node with timestamp T 2. P as source node and U as destination node with timestamp T? So if we start with a bipartite graph where source nodes are always 1 type and destination nodes are always of the other type, we basically need to preprocess the bipartite graphs to add a reverse copy for each edge, is that correct?

**Comment by tedzhouhk** [comment]
Yes, this is correct. If we do not add the reverse edge, then the node in one partition would never have neighbors.

**Comment by yw6vp** [comment]
Thank you, that makes sense.

**Comment by tedzhouhk** [comment]
Hi, edges.csv does not have added reversed links. The reversed links are added in the generated T-CSR data structure ("--add_reverse" flag in gen_graph.py).

**Comment by yw6vp** [comment]
Got it, I was actually just checking gen_graph.py and saw that option. Thanks for the really quick response! 

So just to confirm, even after data preprocessing, edges.csv doesn't have reverse links, the T-CSR data structures (all the *.npz files) are the only only files containing reverse links right? 

Then in train.py, only samplers are aware of the reverse links so they can collect neighbors for all node types, the rest of the code that iterates through edges just follows edges.csv chronologically, correct?

**Comment by tedzhouhk** [comment]
Right.
