### ISSUE TITLE
recent sampling, will it sample the targeted linked neighbor?

### ISSUE THREAD

**Issue by CongWeilin** [amazon-research/tgl#7]
Hi, I am having a questions on whether sampler_core will sample the neighbors that we want to predict.

For example, we want to predict (v_i, v_j) at time t. I did some test on that ParallelSampler, it seems like when sample the subgraph for node v_i at time t, the node v_j is also sampled. However, in real world application it shouldn’t. 

I think instead of sample neighbors using the time stamp of the root node, we have to substract a very small number at https://github.com/amazon-research/tgl/blob/931eb3c33055ab8c7961b91ca2e65a46b0573bc2/train.py#L169 so that it won’t sample other node that have the same time stamps as the root node

I am not sure if I missed something… please feel free to correct me if I was wrong.

**Comment by tedzhouhk** [comment]
Hi, it is possible that v_j is sampled if v_i and v_j have previous interactions before time t. To prevent information leak when we want to predict (v_i, v_j) at time t, here we only enforce that we sample neighbors through edges with timestamps < t (for example [here ](https://github.com/amazon-research/tgl/blob/931eb3c33055ab8c7961b91ca2e65a46b0573bc2/sampler_core.cpp#L300) in sampler_core.cpp). 

Thanks.
